data_entry/views.py
from inspect import currentframe

from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_required, current_user
from database.tables import ApplianceTemplate, JourneyTemplate, CarbonLog
from data_entry.forms import TypeForm, ApplianceForm, TransportForm
from database.enums import LogTypes
from config import db

data_entry_bp = Blueprint('data_entry', __name__, template_folder='templates')

@data_entry_bp.route('/form', methods=['GET', 'POST'])
@login_required
def type_off_form():
    form = TypeForm()
    if form.validate_on_submit():
        if form.type.data == 'Appliance':
            return redirect(url_for('data_entry.appliance'))
        elif form.type.data == 'Transport':
            return redirect(url_for('data_entry.transport'))
    return render_template('data_entry/form.html', form=form)


@data_entry_bp.route('/appliance', methods=['GET', 'POST'])
@login_required
def appliance():
    form = ApplianceForm()
    if form.validate_on_submit():
        userid = current_user.get_id()
        appliance_name = form.appliance.data
        wattage = form.wattage.data
        is_public = form.is_public.data
        start_time = form.start_time.data
        end_time = form.end_time.data
        new_appliance = ApplianceTemplate(template_name=appliance_name, wattage=wattage, user_id=userid, is_public=is_public)
        new_carbon_log = CarbonLog(template_type=LogTypes.appliance, start_time=start_time, end_time=end_time, user_id=userid)
        db.session.add(new_appliance)
        db.session.add(new_carbon_log)
        db.session.commit()
        flash('Appliance form successfully submitted')
    return render_template('data_entry/appliance.html', form=form)

@data_entry_bp.route('/transport', methods=['GET', 'POST'])
@login_required
def transport():
    form = TransportForm()
    if form.validate_on_submit():
        userid = current_user.get_id()
        mode_name=form.transport.data
        carbon_per_km = 0
        if mode_name == 'Car (Petrol)':
            carbon_per_km = 165
        elif mode_name == 'Car (Diesel)':
            carbon_per_km = 170
        elif mode_name == 'Train':
            carbon_per_km = 32
        elif mode_name == 'Bus':
            carbon_per_km = 75
        elif mode_name == 'Plane':
            carbon_per_km = 246
        elif mode_name == 'Motorbike':
            carbon_per_km = 80
        elif mode_name == 'Bicycle':
            carbon_per_km = 21
        is_public = form.is_public.data == "True"
        start_time = form.start_time.data
        end_time = form.end_time.data
        distance_unit = form.distance_unit.data
        distance = form.distance.data
        if distance_unit == 'Miles':
            distance = distance * 1.609
        new_transport = JourneyTemplate(template_name=mode_name, user_id=current_user.get_id(), is_public=is_public,
                                        carbon_per_km=carbon_per_km)
        db.session.add(new_transport)
        db.session.commit()
        new_carbon_log = CarbonLog(template_type=LogTypes.trip, start_time=start_time, end_time=end_time,
                                   user_id=userid, journey_distance=distance, template_id=new_transport.template_id)
        db.session.add(new_carbon_log)
        db.session.commit()
        flash('Transport form successfully submitted')
    return render_template('data_entry/transport.html', form=form)

education/views.py
import random
from flask import Blueprint, Response, render_template, request

from flask_login import current_user
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, DecimalField
from matplotlib.figure import Figure
import requests
import json
from database.enums import Roles
from database.tables import User, CarbonLog

from matplotlib import pyplot
import base64
from io import BytesIO
from config import db
from database import neso_api

import datetime

import config

education_bp = Blueprint('education', __name__, template_folder='templates')

days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]

class LocationForm(FlaskForm):
    latitude = DecimalField("Latitude (degrees)")
    longitude = DecimalField("Longitude (degrees)")
    submit = SubmitField("Calculate!")

def create_monthly_graph(data_in):
    pyplot.figure(figsize=[15.0,5.0])
    pyplot.bar(months, [data_in["outputs"]["monthly"]["fixed"][i]["E_m"] for i in range(12)])
    pyplot.title("Energy Production by Month")
    pyplot.xlabel("Month")
    pyplot.ylabel("Production (kWh)")
    buf = BytesIO()
    pyplot.savefig(buf, format="png", transparent=True)
    
    # Embed the result in the html output.
    data = base64.b64encode(buf.getbuffer()).decode("ascii")
    return data

def create_angle_pie(angle, label, title, colour, startangle):
    pyplot.figure()
    pyplot.title(title)
    reverse = False
    if(angle < 0):
        angle = abs(angle)
        reverse = True
        
    pyplot.pie([angle, 360 - angle], labels=[label, ""], colors=[colour, "lightgray"], startangle=startangle, counterclock=reverse, shadow=True)
    buf = BytesIO()
    pyplot.savefig(buf, format="png", transparent=True)
    
    # Embed the result in the html output.
    data = base64.b64encode(buf.getbuffer()).decode("ascii")
    return data

def create_user_carbon_graph():
    dateToday = datetime.date.today()
    
    dayLabels = []
    our_data = []
    
    average_data = []
    
    for i in range(7):
        date = (dateToday - datetime.timedelta(days=i))
        dayLabels.insert(0,days[date.weekday()])
        our_data.insert(0, CarbonLog.get_global_carbon_total(date - datetime.timedelta(days=1), date)[0])
        
        request = f'https://api.carbonintensity.org.uk/intensity/date/{date.isoformat()}'
        response = requests.get(request)
        _data = response.json()
        intensity = 0.0
        for i in range(48):
            actual = _data['data'][i]["intensity"]["actual"]
            if actual != None:
                intensity += actual
            else:
                _data['data'][i]["intensity"]["forecast"]
        intensity /= 48.0
        average_data.insert(0, intensity)
    
    pyplot.figure()
    pyplot.plot(dayLabels, our_data, label = "our users")
    pyplot.plot(dayLabels, average_data, label="average in the UK")
    pyplot.ylabel("Carbon levels (gCO₂/kWh)")
    pyplot.legend()
    buf = BytesIO()
    pyplot.savefig(buf, format="png", transparent=True)
    
    # Embed the result in the html output.
    data = base64.b64encode(buf.getbuffer()).decode("ascii")
    
    average_percentage = 0.0
    for i in range(7):
        average_percentage += (float(our_data[i]) / float(average_data[i])) * 100.0
    
    average_percentage = round(average_percentage / 7.0)
    
    return data, average_percentage

@education_bp.route("/information")
def information():
    
    global_eco_points = db.session.execute(db.select(db.func.sum(User.ecopoints))).scalar()
    
    data, average_percentage = create_user_carbon_graph()
    
    return render_template("education/information.html", global_eco_points = global_eco_points, graph_data = data, average_percentage = average_percentage)

@education_bp.route("/sunTracker", methods=['GET', 'POST'])
def sunTracker():
    lat = request.args.get("lat")
    lon = request.args.get("lon")
    if lat == None or lon == None:
        return render_template("education/sunTracker.html", error=False)

    apiRequest = "https://re.jrc.ec.europa.eu/api/PVcalc?lat={}&lon={}&peakpower=1&loss=14&optimalangles=1&fixed=1&outputformat=json".format(lat,lon)

    _data = requests.get(apiRequest)
    
    if _data.ok:
    
        print("\n\n request: " , apiRequest, "\n\n")
        
        print("\n\n data is as follows: \n")
        
        print(_data.text)
        
        dataJson = _data.json()

        ed = dataJson["outputs"]["totals"]["fixed"]["E_d"]
        #NOTE: this number represents "peak" daily power for solar panels, 4kWh
        best_ed = 4.0
        efficiency = int((ed / best_ed) * 100.0)

        best_em = 0.0
        best_month = "None"
        
        for i in range(12):
            em = dataJson["outputs"]["monthly"]["fixed"][i]["E_m"]
            if em > best_em:
                best_em = em
                best_month = months[i]
        
        azimuth = dataJson["inputs"]["mounting_system"]["fixed"]["azimuth"]["value"]
        slope = dataJson["inputs"]["mounting_system"]["fixed"]["slope"]["value"]

        return render_template("education/sunTracker.html", data=dataJson, graph = create_monthly_graph(dataJson), slopePie = create_angle_pie(slope, f"{slope}°", "Optimal slope (vertical) angle", "red", 180),azimuthPie = create_angle_pie(azimuth, f"{azimuth}° North", "Optimal azimuth (horizontal) angle", "blue", 90), efficiency = efficiency, best_month = best_month, best_em = best_em, city="", latitude=lat, longitude=lon, success=True)
    else:
        return render_template("education/sunTracker.html", error=True)

game/views.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user
from database.tables import User, Friend

game_bp = Blueprint('game', __name__, template_folder='templates')

@game_bp.route('/leaderboard')
@login_required
def leaderboard():

    user_list = User.query.all()
    all_friends = []
    all_friends_ordered = []
    
    for i in range(1, len(user_list)):
        if (Friend.check_friends(current_user.user_id, user_list[i].user_id)):
            all_friends.append(user_list[i])

    for i in range(1,len(all_friends)):
        initial_user = all_friends[i]
        initialval = all_friends[i].ecopoints
        j = i-1

        while j >= 0 and initialval < all_friends[j].ecopoints:
            all_friends[j + 1] = all_friends[j]
            j -= 1
        all_friends[j + 1] = initial_user
        
    for i in range (len(all_friends)-1,-1,-1):

        all_friends_ordered.append(all_friends[i])

    return render_template('game/leaderboard.html', users = all_friends_ordered, len=len(all_friends_ordered))

@game_bp.route('/game')
def game():
    return render_template('game/game.html')

user/views.py
from flask import Blueprint, flash, redirect, render_template, url_for
from flask_login import login_user, logout_user, current_user, login_required
import pyotp
from argon2 import PasswordHasher
from database.enums import Roles
from database.tables import User
from app_email.tasks import send_verification_email
from user.forms import RegistrationForm, LoginForm
from config import db

user_bp = Blueprint('user', __name__, template_folder='templates')

@user_bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        flash("You are already logged in.", "success")
        return redirect(url_for('index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        if User.query.filter_by(email=form.email.data).first():
            flash("Email already in use.", "danger")
            return render_template("user/register.html", form=form)
        mfa_key = pyotp.random_base32()
        ph = PasswordHasher()
        new_user = User(email=form.email.data,
                        username=form.username.data,
                        password=ph.hash(form.password.data),
                        role=Roles.user,
                        first_name=form.firstname.data,
                        last_name=form.lastname.data,
                        mfa_key=mfa_key,
                        mfa_enabled=False
                        )
        db.session.add(new_user)
        db.session.commit()
        flash('Account Created', category='success')
        flash('MFA must be enabled before account use', category='warning')
        uri = str(pyotp.totp.TOTP(new_user.mfa_key).provisioning_uri(new_user.email, "Carbon Cruncher"))
        return render_template("user/mfasetup.html", secret=mfa_key, uri=uri)
    return render_template('user/register.html', form=form)

@user_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        flash("You are already logged in.", "success")
        return redirect(url_for('index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.verify_password(form.password.data):
            if pyotp.TOTP(user.mfa_key).verify(form.mfapin.data):
                if not user.mfa_enabled:
                    user.update_mfa()
                flash('Login Successful', category='success')
                login_user(user)
                if not user.email_sent():
                    send_verification_email(user)
                return redirect(url_for('user.profile'))
            if not user.mfa_enabled:
                flash('MFA must be enabled before account use', category='warning')
                uri = str(pyotp.totp.TOTP(user.mfa_key).provisioning_uri(user.email, "Carbon Cruncher"))
                return render_template('user/mfasetup.html', secret=user.mfa_key, uri=uri)
        flash('Login Failed', category='danger')
        return redirect(url_for('user.login'))
    return render_template('user/login.html', form=form)

@user_bp.route('/profile')
@login_required
def profile():
    return render_template('user/profile.html', current_user = current_user)

@user_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('index'))

templates/base.html
<!doctype html>
<html>
  <head>
    {% block head %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{{url_for('static', filename='icon.ico')}}">
    {% endblock %}
    <style>
        @keyframes shake_strong {
            0% {rotate:0deg;}
            25% {rotate:5deg;}
            50% {rotate:0deg;}
            75% {rotate:-5deg;}
            100% {rotate:0deg;}
        
        }

        @keyframes shake_light {
            0% {rotate:0deg;}
            25% {rotate:2deg;}
            50% {rotate:0deg;}
            75% {rotate:-2deg;}
            100% {rotate:0deg;}
        
        }

        @font-face {
            font-family: myFirstFont;
            src: url({{url_for('static', filename='Gontserrat-Medium.ttf')}});
        }

        .navicon{
            rotate:0deg;
            color: #000000;
        }

        .navicon-light{
            rotate:0deg;
            color: #000000;
        }

        .navicon:hover{
            animation-name: shake_strong;
            animation-duration: 0.2s;
            color: #ffffff;
        }

        .navicon-light:hover{
            animation-name: shake_light;
            animation-duration: 0.2s;
            color: #ffffff;
        }
    </style>

  </head>
  <body style="background-color: #cffff9; font-family: myFirstFont;">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq" crossorigin="anonymous"></script>
    
    <nav
      class="navbar navbar-expand-sm navbar-light" style="padding: 0px; width: 100%; margin: 0; position:sticky; top:0px; z-index: 99;"
  >
      <div class="container-fluid" style="background-color: #8ad87d; padding-left: 30px; padding-right: 30px; width: 100%; border-radius: 0px 0px 25px 25px; margin: 0;  border: 4px; border-top: 0px; border-style: solid; border-color: #54834c;">
          <a
              class="text-center text-decoration-none navicon"
              href="{{url_for('data_entry.type_off_form')}}"
              style="width:200px;"
              ><img src="{{url_for('static', filename='document.png')}}" style="width:50px"><br>Log Data</a
          >
          <a
              class="text-center text-decoration-none navicon"
              href="{{url_for('education.sunTracker')}}"
              style="width:200px;"
              ><img src="{{url_for('static', filename='sun.png')}}" style="width:50px"><br>Sun Tracker</a
          >
          <a
              class="text-center text-decoration-none navicon"
              href="{{url_for('education.information')}}"
              style="width:200px;"
              ><img src="{{url_for('static', filename='trophy (1).png')}}" style="width:50px"><br>Global User Data</a
          >
          <a
          class="text-center text-decoration-none navicon"
          href="{{url_for('index')}}"
          style="width:200px;"
          ><img src="{{url_for('static', filename='LOGO.png')}}" style="width:100px"></a
          >
          <a
              class="text-center text-decoration-none navicon"
              href="{{url_for('game.game')}}"
              style="width:200px;"
              ><img src="{{url_for('static', filename='paint-roller.png')}}" style="width:50px"><br>Decorate</a
          >
          {% if current_user.is_authenticated %}
          <a
              class="text-center text-decoration-none navicon"
              href="{{url_for('graph.redirect_to_latest_week')}}"
              style="width:200px;"
              ><img src="{{url_for('static', filename='user.png')}}" style="width:50px"><br>{{current_user.username}}</a
          >
          <a
              class="text-center text-decoration-none navicon"
              href="{{url_for('user.logout')}}"
              style="width:200px;"
              ><img src="{{url_for('static', filename='logout.png')}}" style="width:50px"><br>Log Out?</a
          >
          {% else %}
          <span style="width: 200px"></span>
          <a
              class="text-center text-decoration-none navicon"
              href="{{url_for('user.login')}}"
              style="width:200px;"
              ><img src="{{url_for('static', filename='login.png')}}" style="width:50px"><br>Log In / Register</a
          >
          {% endif %}
          
      </div>
  </nav>
    
    <div id="content" style="position:relative;">{% block content %}{% endblock %}</div>
  
    
  </body>
</html>

templates/index.html
{% extends "base.html" %}
{% block title %}Carbon Cruncher - Home Page{% endblock %}

{% block content %}


<h1 class="text-center" style="padding-top: 50px; font-size: 75px">CARBON CRUNCHER</h1>
<h2 class="text-center" style="padding-top : 20px; font-size: 50px">Creating a better world, one day at a time!</h2>
<h3 class="text-center" style="padding-top: 20px; font-size: 20px">Welcome to Carbon Cruncher! Here you can earn Ecopoints by recording all the ways you improve your carbon footprint every day! <br><br> Log in / Register from the top bar! </h3>

<iframe src="{{url_for('game.game')}}"></iframe>

{% endblock %}