user/forms.py
from flask_wtf import FlaskForm, RecaptchaField
from wtforms import StringField, PasswordField, SubmitField, EmailField
from wtforms.validators import DataRequired, EqualTo, Length, Regexp, Email


class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(),
                                                   Length(min=2, max=20),
                                                   Regexp('^[a-zA-Z-]+$', message="Only letters and hyphens are allowed")])
    email = EmailField('Email', validators=[DataRequired(), Email()])
    firstname = StringField('First Name', validators=[DataRequired(),
                                                      Regexp('^[a-zA-Z-]+$', message="Only letters and hyphens are allowed")])
    lastname = StringField('Last Name', validators=[DataRequired(),
                                                    Regexp('^[a-zA-Z-]+$', message="Only letters and hyphens are allowed")])
    password = PasswordField('Password', validators=[DataRequired(),
                                                     Length(8, 15, message='Password must be 8 to 15 characters long'),
                                                     Regexp('.*[A-Z]', message='Password must contain at least one upper case letter'),
                                                     Regexp('.*[a-z]', message='Password must contain at least one lower case letter'),
                                                     Regexp('.*\d', message='Password must contain at least one number'),
                                                     Regexp('.*\W', message='Password must contain at least one special character')])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password', message='Both password fields must be equal!')])
    submit = SubmitField('Register')

class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    mfapin = StringField('MFA Pin')
    recaptcha = RecaptchaField()
    submit = SubmitField('Log In')

user/views.py
from flask import Blueprint, flash, redirect, render_template, url_for
from flask_login import login_user, logout_user, current_user, login_required
import pyotp
from argon2 import PasswordHasher
from database.enums import Roles
from database.tables import User
from app_email.tasks import send_verification_email
from user.forms import RegistrationForm, LoginForm
from config import db

user_bp = Blueprint('user', __name__, template_folder='templates')

@user_bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        flash("You are already logged in.", "success")
        return redirect(url_for('index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        if User.query.filter_by(email=form.email.data).first():
            flash("Email already in use.", "danger")
            return render_template("user/register.html", form=form)
        mfa_key = pyotp.random_base32()
        ph = PasswordHasher()
        new_user = User(email=form.email.data,
                        username=form.username.data,
                        password=ph.hash(form.password.data),
                        role=Roles.user,
                        first_name=form.firstname.data,
                        last_name=form.lastname.data,
                        mfa_key=mfa_key,
                        mfa_enabled=False
                        )
        db.session.add(new_user)
        db.session.commit()
        flash('Account Created', category='success')
        flash('MFA must be enabled before account use', category='warning')
        uri = str(pyotp.totp.TOTP(new_user.mfa_key).provisioning_uri(new_user.email, "Carbon Cruncher"))
        return render_template("user/mfasetup.html", secret=mfa_key, uri=uri)
    return render_template('user/register.html', form=form)

@user_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        flash("You are already logged in.", "success")
        return redirect(url_for('index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.verify_password(form.password.data):
            if pyotp.TOTP(user.mfa_key).verify(form.mfapin.data):
                if not user.mfa_enabled:
                    user.update_mfa()
                flash('Login Successful', category='success')
                login_user(user)
                if not user.email_sent():
                    send_verification_email(user)
                return redirect(url_for('user.profile'))
            if not user.mfa_enabled:
                flash('MFA must be enabled before account use', category='warning')
                uri = str(pyotp.totp.TOTP(user.mfa_key).provisioning_uri(user.email, "Carbon Cruncher"))
                return render_template('user/mfasetup.html', secret=user.mfa_key, uri=uri)
        flash('Login Failed', category='danger')
        return redirect(url_for('user.login'))
    return render_template('user/login.html', form=form)

@user_bp.route('/profile')
@login_required
def profile():
    return render_template('user/profile.html', current_user = current_user)

@user_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('index'))

templates/user/login.html
{% extends "base.html" %}
{% block title %}Carbon Cruncher - Log In{% endblock %}

{% block content %}
    <h1 class="text-center" style="padding-top: 50px; font-size: 50px">Log In</h1>
    <h3 class="text-center" style="padding-top: 20px; font-size: 20px">Complete the form below to log in to your account</h3>
    <h3 class="text-center" style="padding-top: 20px; font-size: 20px">
        Don't have an account yet?
        <a href="{{url_for('user.register')}}">Register</a>
        instead
    </h3>
    <div class="container align-center" style="width: 50%;">
        <form method="POST">
            <div style="text-align: left">
                {% with messages = get_flashed_messages(with_categories=true) %}
                {% for category, message in messages %}
                {{ message }}
                        <!--  Need to implement actual working close button-->
                        <button type="button" class="btn-close" data-bs-dismiss="alert" onclick=delete_flash(this)>
                            <span>&times;</span>
                        </button>
                    {% endfor %}
                {% endwith %}
                {% if form %}
                    {{ form.csrf_token() }}
                    <div class="form-group">
                        {{ form.email.label }}<span style="color: red">*</span>
                        {{ form.email(class="form-control") }}
                        <span style="color: red">
                                    {% for error in form.email.errors %}
                                        <br>
                                        {{ error }}
                                    {% endfor %}
                                    </span>
                    </div>
                    <div class="form-group">
                        {{ form.password.label }}<span style="color: red">*</span>
                        {{ form.password(class="form-control") }}
                        <span style="color: red">
                                    {% for error in form.password.errors %}
                                        <br>
                                        {{ error }}
                                    {% endfor %}
                                    </span>
                    </div>
                    <div class="form-group">
                        {{ form.mfapin.label }}<span style="color: red">*</span>
                        {{ form.mfapin(class="form-control") }}
                    </div>
                    <div class="container-fluid" style="padding-top: 20px; width:50%;">
                        <div class="form-group">
                            {{ form.recaptcha }}
                        </div>
                        <div style="padding-top: 20px;">
                            {{ form.submit(class="btn btn-success", style="width:100%;") }}
                        </div>
                    </div>
                {% endif %}
            </div>
        </form>
        
    </div>
{% endblock %}

templates/user/mfasetup.html
{% extends "base.html" %}
{% block title %}Carbon Cruncher - MFA Setup{% endblock %}

{% block content %}
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% for category, message in messages %}
            <div class="alert alert-{{ category }} mt-3 alert-dismissible" role="alert">
                {{ message }}
                <!--  Need to implement actual working close button-->
                <button type="button" class="btn-close" data-bs-dismiss="alert" onclick=delete_flash(this)>
                    <span>&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endwith %}
    <h1 class="text-center" style="padding-top: 50px; font-size: 50px">MFA setup</h1>
    <h3 class="text-center" style="padding-top: 20px; font-size: 20px">Almost there! Please set up<br>multi-factor authentication<br>to validate your account</h3>
    <div style="padding-top: 50px; width:50%;" class="text-center container">
        <p>Open Microsoft Authenticator or Google Authenticator</p>
        <p>Select Add New Account</p>
        <p>Manually Enter or Scan the QR Code Below</p>
        <h2>Code</h2>
        <p>{{ secret }}</p>
        <h2>QR</h2>
        <img src="{{ qrcode(uri, box_size=5, border=5) }}">
        <p>Once you have entered the link please click <a href="./login">here</a></p>
    </div>
{% endblock %}

templates/user/profile.html
{% extends "base.html" %}
{% block title %}Carbon Cruncher - Profile{% endblock %}

{% block content %}
<h1 class="text-center" style="padding-top: 50px; font-size: 50px">Profile</h1>
<h3 class="text-center" style="padding-top: 20px; font-size: 20px">View your User Profile</h3>
<div style="padding-top: 50px; width: 50%;" class="container text-center">
    <h3>Username: {{current_user.username}}
        {% if current_user.is_admin %}
         [ADMIN]
        {% endif %}
    </h3>
    <h3>Real name: {{current_user.first_name}} {{current_user.last_name}}</h3>
    <h3>Email address: {{current_user.email}}</h3>
    <h3><img src="{{url_for('static', filename='coin.png')}}" width="50px">Ecopoints: {{current_user.ecopoints}}</h3>
</div>
{% endblock %}

templates/user/register.html
{% extends "base.html" %}
{% block title %}Carbon Cruncher - Register{% endblock %}

{% block content %}
    <h1 class="text-center" style="padding-top: 50px; font-size: 50px">Registration</h1>
    <h3 class="text-center" style="padding-top: 20px; font-size: 20px">Complete the form below to create an account</h3>
    <h3 class="text-center" style="padding-top: 20px; font-size: 20px">
        Already have an account?
        <a href="{{url_for('user.login')}}">Log In</a>
        instead
    </h3>
    
    <div class="container align-center" style="width: 50%;">

        <form method="POST">
            <div style="text-align: left">
                {{ form.csrf_token() }}
                <div>
                    {% with messages = get_flashed_messages(with_categories=true) %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }} mt-3 alert-dismissible" role="alert">
                                {{ message }}. Go to <a href="{{ url_for('user.login') }}">login page</a>.
                                <!--  Need to implement actual working close button-->
                                <button type="button" class="btn-close" data-bs-dismiss="alert" onclick=delete_flash(this)>
                                    <span>&times;</span>
                                </button>
                            </div>
                        {% endfor %}
                    {% endwith %}
                </div>
                <div class="form-group">
                    {{ form.username.label }}<span style="color: red">*</span>
                    {{ form.username(class="form-control") }}
                    <span style="color: red">
                                {% for error in form.username.errors %}
                                    <br>
                                    {{ error }}
                                {% endfor %}
                                </span>
                </div>
                <div class="form-group">
                    {{ form.email.label }}<span style="color: red">*</span>
                    {{ form.email(class="form-control") }}
                    <span style="color: red">
                                {% for error in form.email.errors %}
                                    <br>
                                    {{ error }}
                                {% endfor %}
                                </span>
                </div>
                <div class="form-group">
                    {{ form.firstname.label }}<span style="color: red">*</span>
                    {{ form.firstname(class="form-control") }}
                    <span style="color: red">
                                {% for error in form.firstname.errors %}
                                    <br>
                                    {{ error }}
                                {% endfor %}
                                </span>
                </div>
                <div class="form-group">
                    {{ form.lastname.label }}<span style="color: red">*</span>
                    {{ form.lastname(class="form-control") }}
                    <span style="color: red">
                                {% for error in form.lastname.errors %}
                                    <br>
                                    {{ error }}
                                {% endfor %}
                                </span>
                </div>

                </div>
                <div class="form-group">
                    {{ form.password.label }}<span style="color: red">*</span>
                    {{ form.password(class="form-control") }}
                    <span style="color: red">
                                {% for error in form.password.errors %}
                                    <br>
                                    {{ error }}
                                {% endfor %}
                                </span>
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label }}<span style="color: red">*</span>
                    {{ form.confirm_password(class="form-control") }}
                    {% for error in form.confirm_password.errors %}
                        {{ error }}
                    {% endfor %}
                </div>
                <div style="padding-top:20px; width:50%" class="container-fluid">
                    {{ form.submit(class="btn btn-success",style="width:100%;") }}
                </div>
            </div>
        </form>
    </div>
{% endblock %}